name: Generate Docs
on:
  schedule:
    - cron: "0/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate Documentation
        uses: elastic/docs-builder/actions/generator@main
        with:
          output: "docs"
      - name: get current date time
        run: echo "TIME=$(date '+%Y-%M-%d %H:%m:%S')" >> ${GITHUB_ENV}
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          # Stage the file, commit and push
          git add docs
          git commit -m "Doc generation: ${{ env.TIME }}"
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          git push
