name: Generate Docs
on:
  schedule:
    - cron: "0/5 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
      packages: write
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate Documentation
        uses: elastic/docs-builder/actions/generator@main
        with:
          output: "docs"

      - name: get current date time
        run: echo "TIME=$(date '+%Y-%M-%d %H:%m:%S')" >> ${GITHUB_ENV}
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          # Stage the file, commit and push
          git add docs
          git commit -m "Doc generation: ${{ env.TIME }}"
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          git push

      - name: Publish Github
        uses: elastic/docs-builder/actions/publish@main
        id: deployment

  vercel:
    runs-on: ubuntu-latest
    needs: [generate]
    permissions:
      pages: write
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build Docs
        uses: elastic/docs-builder@main

      - name: Publish Vercel
        uses: elastic/docs-builder/actions/publish-vercel@main
        id: deployment-vercel
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
